# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170211_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affilate_membership',
            field=models.BooleanField(default=False, help_text='FOR CLIENT AFFILIATED TO SUBSCRIBING INSTITUTION'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='phone number in this format +2348076222307', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
