# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('profiles', '0005_auto_20170211_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliates.Institution'),
        ),
        migrations.AddField(
            model_name='profile',
            name='membership_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
