# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170212_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership_code',
            field=models.CharField(blank=True, help_text='Matric Number or Identification Number issued by your institution', max_length=25, null=True),
        ),
    ]
