# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170214_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='affilate_membership',
            new_name='affiliate_membership',
        ),
    ]
