# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_manager',
            new_name='manager',
        ),
    ]
