# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_membership_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
