# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0015_auto_20170212_1205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('MT', 'Mobile Transfer'), ('BP', 'Bank Payment'), ('AP', 'Affiliate Privilege'), ('IB', 'Internet Banking'), ('CC', 'Credit Card')], default='MT', max_length=20)),
                ('data_requests', models.ManyToManyField(to='sales.UserRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
