# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='affiliate_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='data_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
