# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_auto_20170217_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='sales_id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
