# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_auto_20170218_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cost_with_vats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='data_cost',
            field=models.IntegerField(default=0),
        ),
    ]
