# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('checkouts', '0004_auto_20170218_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliates.Institution'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='institution_code',
            field=models.CharField(blank=True, help_text='Matric Number or Identification Number issued by your institution', max_length=25, null=True),
        ),
    ]
