# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0005_auto_20170219_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='institution_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
