# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0007_auto_20170222_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'permissions': (('can_approve_transaction', 'Approve transaction approval request sent to affiliate manager'), ('can_disapprove_transaction', 'dispprove transaction apprroval request  sent to affiliate manager'))},
        ),
    ]
