# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0009_auto_20170224_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_mode',
            field=models.CharField(choices=[('BP', 'Bank Payment'), ('AP', 'Affiliate Privilege')], default='Bp', max_length=20),
        ),
    ]
