# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name_plural': 'Components'},
        ),
        migrations.AlterField(
            model_name='concattable',
            name='code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
