# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170122_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='price',
        ),
    ]
