# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_frequency_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.PositiveSmallIntegerField(blank=True, default=1960, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='concattable',
            name='avail_from',
        ),
        migrations.RemoveField(
            model_name='concattable',
            name='avail_to',
        ),
        migrations.AddField(
            model_name='concattable',
            name='avail_yrs',
            field=models.ManyToManyField(to='sales.Years'),
        ),
    ]
