# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170131_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='factor',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
