# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20170202_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='factor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
