# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20170202_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(blank=True, default='1960s', max_length=200, null=True),
        ),
    ]
