# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='period_sum_factor',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='data_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='frequency',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='level_of_agregation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='table',
            field=models.CharField(max_length=3),
        ),
    ]
