# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20170203_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='comment',
            field=models.TextField(default='Write your comments are. Thank you!'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='categories_of_aggregation',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name=sales.models.CategoryOfAggregation),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='data_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='period_sum_factor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='variables',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='variables',
            field=models.ManyToManyField(to='sales.Variable'),
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='years',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='years',
            field=models.ManyToManyField(to='sales.Years'),
        ),
    ]
