# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20170204_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Frequency'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='level_of_aggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.LevelOfAggregation'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Table'),
        ),
    ]
