# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20170206_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='categories_of_aggregation',
            field=models.ManyToManyField(help_text='To select multiple hold down ctrl botton on the keyboard or ctrl A to select all', to='sales.CategoryOfAggregation'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='variables',
            field=models.ManyToManyField(help_text='To select multiple hold down ctrl botton on the keyboard or ctrl A to select all', to='sales.Variable'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='years',
            field=models.ManyToManyField(help_text='To select multiple hold down ctrl botton on the keyboard or ctrl A to select all', to='sales.Years'),
        ),
    ]
